Fix ExtractDestination() for ColdStaking
navcoin/navcoin-core pull request #898
Opened 2021-12-04 11:19 UTC by aguycalled

What to test:

* Cold Staking works correctly with this patch

2021-12-04 12:06 UTC, mxaddict commented
Building with Ubuntu 20.04

2021-12-04 15:23 UTC, mxaddict commented
Testing the cold staking now:

![image](https://user-images.githubusercontent.com/1060905/144714969-d040dfe3-2477-4ca8-b8d4-4bbe75e6804e.png)


Will let this run for a while, will approve once I have had the cold staking running for about an hours

2021-12-04 15:24 UTC, aguycalled commented
Good! It should also get tested that spendable and stakable balances are correctly shown, my tests were successful on that regard.

2021-12-04 15:25 UTC, mxaddict commented
> Good! It should also get tested that spendable and stakable balances are correctly shown, my tests were successful on that regard.

So far tha balances are correct on the UI as well, but will monitor it as it keeps staking.

2021-12-04 15:27 UTC, mxaddict commented
@aguycalled "Pending" balance is only for when a TX adds balance but is not yet staked in a block correct?

2021-12-04 15:42 UTC, aguycalled commented
yes

2021-12-04 15:58 UTC, mxaddict commented
I've setup 2 cold staking nodes and 1 spending node, seems to be working nicely so far, will let these run for a while longer:

![image](https://user-images.githubusercontent.com/1060905/144716086-2e3bf995-b7e8-4a72-8871-dafe731e6d5c.png)

2021-12-04 16:17 UTC, mxaddict approved these changes
I think I'm happy with the testing on this PR, seems all is working with regards to cold staking, also testing some hot wallet staking and was still working as expected.

2021-12-04 19:32 UTC, RealKeyboardWarrior requested changes

2021-12-04 19:32 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +    return (this->size() > 50 &&
must be ==

2021-12-04 19:32 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +    return (this->size() > 27 &&
must be ==

2021-12-04 19:34 UTC, RealKeyboardWarrior requested changes

2021-12-04 19:34 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +            (*this)[27] == OP_ELSE);
why is it not validated beyond this point?

2021-12-04 19:34 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +            (*this)[49] == OP_ELSE);
ditto why is it not validated beyond this point?

2021-12-04 19:40 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +    return (this->size() > 50 &&
nvm - it's just to get the coldstake key

2021-12-04 19:40 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +    return (this->size() > 27 &&
nvm - it's just to get the coldstake key

2021-12-04 19:40 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +            (*this)[27] == OP_ELSE);
nvm - it's just to get the coldstake key

2021-12-04 19:40 UTC, RealKeyboardWarrior commented on src/script/script.cpp
> +            (*this)[49] == OP_ELSE);
nvm - it's just to get the coldstake key

2021-12-04 19:52 UTC, chasingkirkjufell commented
building with ubuntu 20.04 as well, will report any findings

2021-12-05 03:48 UTC, chasingkirkjufell commented
when i try to send coins to the cold staking address the balance isn't correct.
steps:
create 2 wallets, create a coldstaking address v1 with wallet 1 benign spending and wallet 2 being staking
disable staking for both wallets to have better control
send multiple transaction from wallet 1 to the cold staking address
generate a block
![image](https://user-images.githubusercontent.com/38635377/144732681-fdb28286-19fb-44bf-9fa0-09d47f8e3b1e.png)

2021-12-05 03:51 UTC, chasingkirkjufell commented
so it looks like the staking wallet is showing the correct balance since actually there are only 2 groupings that went through? history shows all 5 though. window on the left is from spending wallet while on the right is the staking wallet
![image](https://user-images.githubusercontent.com/38635377/144732720-df8dfe14-2c70-470b-84ff-8c51459193f1.png)

2021-12-05 11:11 UTC, mxaddict commented
@chasingkirkjufell I did not run into any balance issues with my testing, can you give me steps to replicate?

2021-12-05 17:54 UTC, aguycalled commented
![image](https://user-images.githubusercontent.com/24814046/144757619-92e1fb34-a5c3-463b-8226-2eb479f8a003.png)
 
I haven't been able to replicate it. Most likely case is that the first transactions where spent in the following (in case they were sent to a cold staking address with a spending address of that node). Will wait to hear more details to see if we can replicate/confirm.

2021-12-07 02:20 UTC, chasingkirkjufell commented
> ![image](https://user-images.githubusercontent.com/24814046/144757619-92e1fb34-a5c3-463b-8226-2eb479f8a003.png)
> 
> I haven't been able to replicate it. Most likely case is that the first transactions were spent in the following (in case they were sent to a cold staking address with a spending address of that node). Will wait to hear more details to see if we can replicate/confirm.

I noticed that this issue is not related to this PR so I am going to approve this PR for now. Lke your said, it may be because of the outputs were spent again but the transaction history is confusing. For what it's worth, here are a bit more detailed steps.

1. creating 2 wallets and disable staking
2. connect 2nd wallet to first
3. generate 300 blocks on 1st wallet
4. create a coldstaking address v1 with wallet 1 spending and wallet 2 staking
5. send 5 txs to coldstaking address
6. generate more blocks
7. the tab will show all 5 txes but only 2 are actually valid. repair wallet or zapwallettxes does not fix it

2021-12-07 02:20 UTC, chasingkirkjufell approved these changes

2021-12-07 10:53 UTC, merged